research_task:
  description: >
    Research the topic provided by the user and return the most relevant information. Here is the topic: {topic}
  expected_output: >
    A list of the most relevant information with some explanation in markdown format.
  agent: research_agent
